// 종목 리스트
const stockList = [
  {
    name: "비트코인",
    en_name: "bitcoin",
    code: "BTC",
    codes: "KRW-BTC",
    category: "coin",
  },
  {
    name: "이더리움",
    en_name: "ethereum",
    code: "ETH",
    codes: "KRW-ETH",
    category: "coin",
  },
  {
    name: "리플",
    en_name: "xrp",
    code: "XRP",
    codes: "KRW-XRP",
    category: "coin",
  },
  {
    name: "솔라나",
    en_name: "solana",
    code: "SOL",
    codes: "KRW-SOL",
    category: "coin",
  },
  {
    name: "카르다노",
    en_name: "cardano",
    code: "ADA",
    codes: "KRW-ADA",
    category: "coin",
  },
  {
    name: "도지코인",
    en_name: "dogecoin",
    code: "DOGE",
    codes: "KRW-DOGE",
    category: "coin",
  },
  {
    name: "리퍼리움",
    en_name: "refereum",
    code: "RFR",
    codes: "KRW-RFR",
    category: "coin",
  },
  {
    name: "샌드박스",
    en_name: "sandbox",
    code: "SAND",
    codes: "KRW-SAND",
    category: "coin",
  },
  {
    name: "디센트럴랜드",
    en_name: "decentraland",
    code: "MANA",
    codes: "KRW-MANA",
    category: "coin",
  },
  {
    name: "이캐시",
    en_name: "eCash",
    code: "XEC",
    codes: "KRW-XEC",
    category: "coin",
  },
  {
    name: "삼성전자",
    en_name: null,
    code: "005930",
    codes: null,
    category: "stock",
  },
  {
    name: "한국금융지주",
    en_name: null,
    code: "071050",
    codes: null,
    category: "stock",
  },
  {
    name: "POSCO홀딩스",
    en_name: null,
    code: "005490",
    codes: null,
    category: "stock",
  },
  {
    name: "kodex200 선물인버스2x",
    en_name: null,
    code: "252670",
    category: "stock",
  },
];

export default stockList;
