// 종목 리스트
const stockList = [
  {
    name: "비트코인",
    en_name: "Bitcoin",
    code: "BTC",
    codes: "KRW-BTC",
    category: "coin",
  },
  {
    name: "이더리움",
    en_name: "Ethereum",
    code: "ETH",
    codes: "KRW-ETH",
    category: "coin",
  },
  {
    name: "리플",
    en_name: "ripple",
    code: "XRP",
    codes: "KRW-XRP",
    category: "coin",
  },
  {
    name: "솔라나",
    en_name: "Solana",
    code: "SOL",
    codes: "KRW-SOL",
    category: "coin",
  },
  {
    name: "에이다",
    en_name: "Ada",
    code: "ADA",
    codes: "KRW-ADA",
    category: "coin",
  },
  {
    name: "도지코인",
    en_name: "Dogecoin",
    code: "DOGE",
    codes: "KRW-DOGE",
    category: "coin",
  },
  {
    name: "리퍼리움",
    en_name: "Refereum",
    code: "RFR",
    codes: "KRW-RFR",
    category: "coin",
  },
  {
    name: "샌드박스",
    en_name: "Sandbox",
    code: "SAND",
    codes: "KRW-SAND",
    category: "coin",
  },
  {
    name: "디센트럴랜드",
    en_name: "Decentraland",
    code: "MANA",
    codes: "KRW-MANA",
    category: "coin",
  },
  {
    name: "네오",
    en_name: "NEO",
    code: "NEO",
    codes: "KRW-NEO",
    category: "coin",
  },
  {
    name: "이더리움 클래식",
    en_name: "Ethereum Classic",
    code: "ETC",
    codes: "KRW-ETC",
    category: "coin",
  },
  {
    name: "질리카",
    en_name: "Zilliqa",
    code: "ZIL",
    codes: "KRW-ZIL",
    category: "coin",
  },
  {
    name: "이오스",
    en_name: "EOS",
    code: "EOS",
    codes: "KRW-EOS",
    category: "coin",
  },
  {
    name: "카이버네트워크",
    en_name: "Kyber Network",
    code: "KNC",
    codes: "KRW-KNC",
    category: "coin",
  },
  {
    name: "트론",
    en_name: "tron",
    code: "TRX",
    codes: "KRW-TRX",
    category: "coin",
  },
  {
    name: "이캐시",
    en_name: "eCash",
    code: "XEC",
    codes: "KRW-XEC",
    category: "coin",
  },
  {
    name: "비트코인 캐시",
    en_name: "Bitcoin Cash",
    code: "BCH",
    codes: "KRW-BCH",
    category: "coin",
  },
  {
    name: "테조스",
    en_name: "Tezos",
    code: "XTZ",
    codes: "KRW-XTZ",
    category: "coin",
  },
  {
    name: "삼성전자",
    en_name: null,
    code: "005930",
    codes: null,
    category: "stock",
  },
  {
    name: "한국금융지주",
    en_name: null,
    code: "071050",
    codes: null,
    category: "stock",
  },
  {
    name: "POSCO홀딩스",
    en_name: null,
    code: "005490",
    codes: null,
    category: "stock",
  },
  {
    name: "kodex200 선물인버스2x",
    en_name: null,
    code: "252670",
    category: "stock",
  },
];

export default stockList;
